export const indianAirports = [
    { "Delhi": "DEL" },
    { "Mumbai": "BOM" },
    { "Bengaluru": "BLR" },
    { "Hyderabad": "HYD" },
    { "Kolkata": "CCU" },
    { "Chennai": "MAA" },
    { "Ahmedabad": "AMD" },
    { "Pune": "PNQ" },
    { "Goa (Dabolim)": "GOI" },
    { "Goa (Mopa)": "GOX" },
    { "Lucknow": "LKO" },
    { "Guwahati": "GAU" },
    { "Jaipur": "JAI" },
    { "Srinagar": "SXR" },
    { "Kochi": "COK" },
    { "Bhopal": "BHO" },
    { "Indore": "IDR" },
    { "Patna": "PAT" },
    { "Chandigarh": "IXC" },
    { "Bhubaneswar": "BBI" },
    { "Amritsar": "ATQ" },
    { "Ranchi": "IXR" },
    { "Raipur": "RPR" },
    { "Nagpur": "NAG" },
    { "Thiruvananthapuram": "TRV" }
];